# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:

        # Paramétrage de l'affichage de l'image de profil dans la page "mon profil"
        profil:
            quality: 100
            filters:
                scale:
                    dim: [200, 200]

        comment:
            quality: 100
            filters:
                scale:
                    dim: [80, 80]