twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        site_name: '%site_name%'
        google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'